# Generated by Django 5.1.1 on 2024-10-07 19:51

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_adress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adress',
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='default value', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
